-- <문자 함수>

-- UPPER : 대문자로 바꾸기 (LOWER 도 가능)

SELECT UPPER(ENAME) FROM EMP

-- LENGTH : 길이

SELECT LENGTH(ENAME) FROM EMP

-- SUBSTR : 문자열 추출

SELECT SUBSTR(ENAME, 2) FROM EMP

SELECT SUBSTR(ENAME, 1, 2) FROM EMP

SELECT SUBSTR(ENAME, -2) FROM EMP

-- REPLACE : 문자 대체

SELECT REPLACE(ENAME, 'L', 'N') FROM EMP

-- LPAD / RPAD : 빈 공간을 특정 문자로 대체

SELECT LPAD(ENAME, 6, '#') FROM EMP		-- 6자리 중 빈 공간으로 #으로 넣음 (L은 앞쪽을 빈공간으로, R은 뒤쪽을 빈공간으로)
		-- ex) ARI -> ###ARI
-- CONCAT : 문자열 합치기. 이때 두개의 인자만 받을 수 있으므로, 2개 이상일 때는 중첩해야함 

SELECT CONCAT (EMPNO, ENAME) FROM EMP

SELECT CONCAT(EMPNO, ':') AS CONCAT_RESULT FROM EMP

SELECT CONCAT(CONCAT(EMPNO, ':'), ENAME) AS CONCAT_RESULT2 FROM EMP

SELECT EMPNO||':'||ENAME FROM EMP		-- 윗줄과 같은 결과, 여러개 인자를 받을 때에는 CONCAT 대신 ||를 쓰기도 함

-- TRIM : 문자열 자르기

SELECT TRIM(ENAME) FROM EMP		-- 앞 뒤로 공백 제거(중간에 있는 공백은 안됨. 중간 공백은 REPLACE 사용해서 지우기)

SELECT LENGTH(TRIM(ENAME)) FROM EMP		--공백 제거한 길이

SELECT TRIM('W' FROM ENAME) FROM EMP 

SELECT TRIM('   hong   ') FROM EMP

SELECT TRIM(BOTH 'A' FROM ENAME) FROM EMP 	-- BOTH : 양쪽 끝으로 A 삭제

SELECT TRIM(LEADING 'A' FROM ENAME) FROM EMP	-- LEADING : 앞쪽에 A 제거

SELECT TRIM(TRAILING 'A' FROM ENAME) FROM EMP	-- TRAILING : 뒤쪽에 A 제거

-- ROUND / TRUNC / CEIL / FLOOR / MOD : 소수점 반올림 / 버림 / 올림 / 내림 / 나머지
-- ADD_MONTHS : 몇개월 이후
-- NEXT_DAY : 특정 날짜 이후에 지정한 요일
-- TO_CHAR / TO_NUMBER : 숫자, 날짜 데이터를 문자로 변환 / 문자 데이터를 숫자로 변환

SELECT SYSDATE, TO_CHAR(SYSDATE, 'MONTH')AS MONTH FROM DUAL		-- 3월
--DUAL은 테스트용 먹통 테이블(실제 테이블이 아닌 테스트용 테이블)

-- TO_DATE : 문자 데이터를 날짜 데이터로 변환

SELECT TO_DATE('2018-0714', 'YYYY-MM-DD') FROM DUAL		-- 2018-07-14

SELECT TO_DATE('2018-07-14', 'YYYY-MM-DD') AS TODATE1 FROM DUAL	-- 문자를 날짜 포맷으로 출력

SELECT * FROM EMP WHERE HIREDATE > TO_DATE('1981/06/01', 'YYYY/MM/DD')	--1981년 6월 1일 이후 입사 직원 조회


-- <NULL 처리> : 기본 연산은 NULL인 데이터가 포함될 경우 실행되지 않음 따라서 NULL 인 경우 0으로 바꾼 후 실행

UPDATE EMP SET COMM = 0 WHERE COMM IS NULL	-- COMM 열의 값이 NULL인 경우 NULL이 아닌 0으로 바꿈

SELECT SAL + COMM AS TOTAL FROM EMP     -- 데이터 연산


-- <조건 함수>
-- DECODE / CASE

SELECT EMPNO ENAME, JOB, SAL,
DECODE (JOB,
	'MANAGER', SAL*1.1,
	'SALESMAN', SAL*1.05,
	'ANALYST', SAL,
	SAL*1.03)
	AS UPSAL
FROM EMP

SELECT EMPNO, ENAME, JOB, SAL, 
CASE JOB 
	WHEN 'MANAGER' THEN SAL*1.1
	WHEN 'SALESMAN' THEN SAL*1.05
	WHEN 'ANALYST' THEN SAL
	ELSE SAL*1.03
	END AS UPSAL
FROM EMP

SELECT EMPNO, ENAME, COMM,
CASE
	WHEN COMM IS NULL THEN '해당사항 없음'
	WHEN COMM = 0 THEN '수당없음'
	WHEN COMM > 0 THEN '수당 : '
	END AS COMM_TEXT
FROM EMP


--<문자함수 확인문제>

SELECT LENGTH(ENAME) FROM EMP		--1

SELECT LENGTH(ENAME) FROM EMP WHERE JOB='MANAGER'		--2

SELECT ENAME, JOB FROM EMP WHERE COMM IS NULL 		--3

SELECT HIREDATE FROM EMP WHERE COMM IS NOT NULL 	--4

SELECT SUBSTR(ENAME, 2, -1) FROM ERP		--5

SELECT SUBSTR(ENAME, 1,3) FROM EMP		--6

SELECT REPLACE(ENAME, 'K', 'P') FROM EMP		--7

SELECT CONCAT (CONCAT ENPNO, (CONCAT('번은 ', ENAME)), '입니다' FROM EMP e 			--8

SELECT TO_CHAR (HIREDATE, 'MONTH') AS MONTH, TO_CHAR (HIREDATE, 'DAY') AS DAY FROM EMP			--9

SELECT JOB,
CASE JOB
	WHEN 'MANAGER' THEN 'level1'
	WHEN 'SALESMAN' THEN 'level2'
	ELSE 'level3'
	END AS LEVEL_RESULT
FROM EMP			--10
