--<집계, 그룹함수>

--SUM / COUNT / AVG : 합 / 개수/ 평균

SELECT COUNT(*) FROM EMP 		--전체 컬럼 개수

SELECT COUNT(DISTINCT SAL) FROM EMP 		--SAL중 겹치는 데이터를 제외한 데이터의 개수

SELECT AVG(SAL) FROM EMP		--SAL 평균

SELECT AVG(SAL), SUM(SAL) FROM EMP WHERE JOB='SALESMAN'		--SALESMAN의 SAL 평균, 총합

--MIN / MAX : 최소 / 최대

SELECT MIN(SAL), MAX(SAL) FROM EMP

--GROUP BY : 그룹별로 묶을 떄

SELECT DEPTNO, AVG(SAL) FROM EMP GROUP BY DEPTNO		-- DEPTNO별로 묶어서 평균을 냄

SELECT DEPTNO,AVG(SAL) FROM EMP GROUP BY DEPTNO ORDER BY DEPTNO DESC		-- 그룹 별로 평균 낸 것을 DEPTNO 역순으로 정렬

SELECT DEPTNO, AVG(SAL) FROM EMP GROUP BY DEPTNO HAVING AVG(SAL)>=2000 ORDER BY DEPTNO DESC		--HAVING : 조건. 평균 SAL 2000이상인 그룹만

SELECT JOB, COUNT(SAL), SUM(SAL), ROUND(AVG(SAL)) FROM EMP GROUP BY JOB ORDER BY COUNT(SAL)


--<집계, 그룹함수 확인문제>

SELECT COUNT(*) AS TOTAL_EMPLOYEE FROM EMP		--1

SELECT COUNT(ENAME) FROM EMP WHERE DEPTNO=20 OR MGR<=7700		--2

SELECT MIN(SAL) FROM EMP WHERE DEPTNO IN (10, 20)		--3

SELECT MIN(SAL), MAX(SAL), SUM(SAL) FROM EMP		--4

SELECT AVG(SAL) FROM EMP GROUP BY DEPTNO		--5

SELECT DEPTNO, AVG(SAL) FROM EMP GROUP BY DEPTNO ORDER BY DEPTNO	--6

SELECT AVG(SAL) FROM EMP GROUP BY DEPTNO HAVING AVG(SAL)>=2000 ORDER BY DEPTNO DESC		--7

SELECT COUNT(ENAME), AVG(SAL) FROM EMP WHERE JOB='MANAGER'		--8

SELECT COUNT(ENAME) FROM EMP WHERE ENAME LIKE '%S%'		--9

SELECT ENAME FROM EMP WHERE SAL>=3000 AND COMM IS NOT NULL ORDER BY SAL DESC		--10